//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazorm
{
    using System;
    using System.Linq;
    using Lazorm.Attributes;
    using System.ComponentModel.DataAnnotations;
    
    
    [Serializable()]
    [DbTable(Name="test", Remarks="", DatabaseType=DatabaseType.SqLite, ConnectionSettingKeyName="mainKey")]
    public partial class test : DataEntity<test>
    {
        
        private System.Nullable<long> _id;
        
        private string _message;
        
        [DbColumn(Name="id", TypeName="INTEGER", IsPrimaryKey=true, Nullable=true, Length=0)]
        public virtual System.Nullable<long> id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [DbColumn(Name="message", TypeName="TEXT", Nullable=true, Length=0)]
        public virtual string message
        {
            get
            {
                return this._message;
            }
            set
            {
                this._message = value;
            }
        }
        
        public static test? Get(System.Nullable<long> _id)
        {
            test entity = new test();
            entity.id = _id;
            if (!entity.Fill())
            {
                return null;
            }
            return entity;
        }
        
        public static System.Threading.Tasks.Task<test?> GetAsync(System.Nullable<long> _id)
        {
            return ((System.Threading.Tasks.Task<test?>)(System.Threading.Tasks.Task.Run(() => test.Get(_id))));
        }
    }
}
