//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazorm
{
    using System;
    using System.Linq;
    using Lazorm.Attributes;
    using System.ComponentModel.DataAnnotations;
    
    
    [Serializable()]
    [DbTable(Name="test_with_timestamp", Remarks="", DatabaseType=DatabaseType.SqLite, ConnectionSettingKeyName="mainKey")]
    public partial class test_with_timestamp : DataEntity<test_with_timestamp>
    {
        
        private System.Nullable<long> _id;
        
        private string _message;
        
        private string _updated_at;
        
        private string _created_at;
        
        [DbColumn(Name="id", TypeName="INTEGER", IsPrimaryKey=true, Nullable=true, Length=0)]
        public virtual System.Nullable<long> id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [DbColumn(Name="message", TypeName="TEXT", Nullable=true, Length=0)]
        public virtual string message
        {
            get
            {
                return this._message;
            }
            set
            {
                this._message = value;
            }
        }
        
        [DbColumn(Name="updated_at", TypeName="TEXT", Nullable=true, Length=0)]
        public virtual string updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                this._updated_at = value;
            }
        }
        
        [DbColumn(Name="created_at", TypeName="TEXT", Nullable=true, Length=0)]
        public virtual string created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                this._created_at = value;
            }
        }
        
        public static test_with_timestamp? Get(System.Nullable<long> _id)
        {
            test_with_timestamp entity = new test_with_timestamp();
            entity.id = _id;
            if (!entity.Fill())
            {
                return null;
            }
            return entity;
        }
        
        public static System.Threading.Tasks.Task<test_with_timestamp?> GetAsync(System.Nullable<long> _id)
        {
            return ((System.Threading.Tasks.Task<test_with_timestamp?>)(System.Threading.Tasks.Task.Run(() => test_with_timestamp.Get(_id))));
        }
    }
}
