using System;
using System.IO;
using Microsoft.Extensions.CommandLineUtils;

namespace Lazorm 
{
    class Program
    {
        static void Main(string[] args)
        {
            Array.ForEach(args, a => Console.WriteLine(a)); 
            var app = new CommandLineApplication(throwOnUnexpectedArg: true);

            app.Name = nameof(Lazorm);
            app.Description = @"データベースから、エンティティクラスを生成します。";

            app.HelpOption("-h|--help");

            var dbKindArgument = app.Argument(
                name: "kind",
                description: "接続先データベースの製品名を指定します。対応データベース: sqlServer, oracle, mySql",
                multipleValues: false);

            var constrArgument = app.Argument(
                name: "connectionString",
                description: "接続文字列",
                multipleValues: false);

            var tablesArgument = app.Argument(
                name: "tables",
                description: "テーブル名を列挙します。",
                multipleValues: true);

            var outFolderOption = app.Option(
                template: "-o|--out",
                description: "出力先フォルダを指定します。",
                optionType: CommandOptionType.MultipleValue);

            var settingsJsonOption = app.Option(
                template: "-j|--json",
                description: "appsetteings.jsonファイルを指定します。",
                optionType: CommandOptionType.SingleValue);

            var showTablesOption = app.Option(
                template: "-l|--ls|--list",
                description: "テーブル一覧を表示します。",
                optionType: CommandOptionType.NoValue);

            app.OnExecute(() =>
            {
                if (constrArgument.Value == null)
                {
                    // Console.WriteLine("constr: {0} tables:{1} ", constrArgument.Value, tablesArgument.Value);

                    app.ShowHelp();
                    Console.WriteLine(@"使用例：
    dotnet lazorm -- sqlServer 'initial catalog=...' -ls 
    -> テーブル一覧を表示します。

    dotnet lazorm -- sqlServer 'initial catalog=...' users,logs
    -> users,logsテーブルのエンティティクラスをカレントディレクトリに生成します。
    ");
                    return 1;
                }

                Database db = Database.CreateInstance(dbKindArgument.Value, constrArgument.Value);

                if(showTablesOption.HasValue()){
                    Console.WriteLine("===  TABLE NAME  ===\n--------------------");
                    db.GetTableDefs().ForEach(t => 
                        Console.WriteLine("{0} ", t.Name)
                    );
                    return 0;
                }

                var outFolder = Path.Combine(Environment.CurrentDirectory, "Entities", "autoGenerated");
                if (outFolderOption.HasValue())
                {
                    outFolder = outFolderOption.Value();
                    Console.WriteLine("Output directory is specified: {0}", outFolder);
                }

                var keyName = string.Format("{0}Key", db.Schema);
                var generator = new DataEntityGenerator("Lazorm", db, keyName);
                var tableArgsTemp = tablesArgument.Value.Replace(",", " ");
                var regex = new System.Text.RegularExpressions.Regex(" +").Replace(tableArgsTemp, " ");
                var tableArgs = regex.Split(" ");
                Array.ForEach(tableArgs, t => {
                    generator.Generate(t, outFolder);
                });

                JsonSettingWriter.SetAppSettingValue(keyName, constrArgument.Value,
                 settingsJsonOption.Value());
                return 0;
            });

            app.Execute(args);
        }
    }
}
